package com.vispractice.fmc.webservice.processsrv.sb_wf_instance_approvalsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.vispractice.fmc.webservice.support.SimulateHelper;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-07T17:34:01.076+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "SBWFInstanceApprovalSrvService", 
                  wsdlLocation = "http://10.204.115.52:8080/ws/sbWFInstanceApprovalSrv/sbWFInstanceApprovalSrv.wsdl",
                  targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_Instance_ApprovalSrv") 
public class SBWFInstanceApprovalSrvService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://csb.fmc.vispractice.com/SB_WF_Instance_ApprovalSrv", "SBWFInstanceApprovalSrvService");
    public final static QName SBWFInstanceApprovalSrvSoap11 = new QName("http://csb.fmc.vispractice.com/SB_WF_Instance_ApprovalSrv", "SBWFInstanceApprovalSrvSoap11");
    static {
        URL url = null;
        try {
            url = new URL(SimulateHelper.getURI()+"/ws/sbWFInstanceApprovalSrv/sbWFInstanceApprovalSrv.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SBWFInstanceApprovalSrvService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.204.115.52:8080/ws/sbWFInstanceApprovalSrv/sbWFInstanceApprovalSrv.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SBWFInstanceApprovalSrvService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBWFInstanceApprovalSrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBWFInstanceApprovalSrvService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SBWFInstanceApprovalSrvService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SBWFInstanceApprovalSrvService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SBWFInstanceApprovalSrvService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SBWFInstanceApprovalSrv
     */
    @WebEndpoint(name = "SBWFInstanceApprovalSrvSoap11")
    public SBWFInstanceApprovalSrv getSBWFInstanceApprovalSrvSoap11() {
        return super.getPort(SBWFInstanceApprovalSrvSoap11, SBWFInstanceApprovalSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBWFInstanceApprovalSrv
     */
    @WebEndpoint(name = "SBWFInstanceApprovalSrvSoap11")
    public SBWFInstanceApprovalSrv getSBWFInstanceApprovalSrvSoap11(WebServiceFeature... features) {
        return super.getPort(SBWFInstanceApprovalSrvSoap11, SBWFInstanceApprovalSrv.class, features);
    }

}
