package com.vispractice.fmc.webservice.processsrv.sb_wf_instance_approvalsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.vispractice.fmc.csb.sb_wf_instance_approvalsrv.ObjectFactory;
import com.vispractice.fmc.csb.sb_wf_instance_approvalsrv.ProcessRequest;
import com.vispractice.fmc.csb.sb_wf_instance_approvalsrv.ProcessResponse;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-07T17:34:01.070+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_Instance_ApprovalSrv", name = "SBWFInstanceApprovalSrv")
@XmlSeeAlso({com.vispractice.fmc.csb.msgheader.ObjectFactory.class, ObjectFactory.class, com.vispractice.fmc.csb.extendparamcollection.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBWFInstanceApprovalSrv {

    @WebMethod
    @WebResult(name = "processResponse", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_Instance_ApprovalSrv", partName = "processResponse")
    public ProcessResponse process(
        @WebParam(partName = "processRequest", name = "processRequest", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_Instance_ApprovalSrv")
        ProcessRequest processRequest
    );
}
