package com.vispractice.fmc.webservice.callback;
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */


import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.14-SNAPSHOT-88db31a177cff3d0b288bceced1907ad66f447e4
 * 2018-01-22T16:44:07.080+08:00
 * Generated source version: 3.0.14-SNAPSHOT
 * 
 */

@javax.jws.WebService(
                      serviceName = "easWorkflowCommonCallbackWebservice",
                      portName = "EasWorkflowCommonCallbackWebserviceImplPort",
                      targetNamespace = "http://soap.f10.vispractice.com/fssc/eas/boe/core",
//                      wsdlLocation = "http://localhost:9015/fssc-eas-web/apis/ws/fssc/eas/callback/easWorkFlowCommonCallback?wsdl",
                      endpointInterface = "com.vispractice.fmc.webservice.callback.IEasWorkflowCommonCallbackWebservice")
                      
public class EasWorkflowCommonCallbackWebserviceImplPortImpl implements IEasWorkflowCommonCallbackWebservice {

    private static final Logger LOG = Logger.getLogger(EasWorkflowCommonCallbackWebserviceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vispractice.fmc.webservice.callback.IEasWorkflowCommonCallbackWebservice#nodeComplementCallback(com.vispractice.fmc.webservice.callback.WorkFlowParms arg0)*
     */
    public String nodeComplementCallback(com.vispractice.fmc.webservice.callback.WorkFlowParms arg0) { 
    	LOG.info("Executing operation nodeComplementCallback");
    	System.out.println(arg0);
    	try {
    	java.lang.String _return = "";
    	return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
