package com.vispractice.fmc.webservice.callback;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.14-SNAPSHOT-88db31a177cff3d0b288bceced1907ad66f447e4
 * 2018-01-22T16:44:07.209+08:00
 * Generated source version: 3.0.14-SNAPSHOT
 * 
 */
@WebService(targetNamespace = "http://webservice.facade.core.boe.eas.fssc.vispractice.com/", name = "IEasWorkflowCommonCallbackWebservice")
@XmlSeeAlso({ObjectFactory.class})
public interface IEasWorkflowCommonCallbackWebservice {

    @RequestWrapper(localName = "nodeComplementCallback", targetNamespace = "http://webservice.facade.core.boe.eas.fssc.vispractice.com/", className = "com.vispractice.fmc.webservice.callback.NodeComplementCallback")
    @WebMethod
    @ResponseWrapper(localName = "nodeComplementCallbackResponse", targetNamespace = "http://webservice.facade.core.boe.eas.fssc.vispractice.com/", className = "com.vispractice.fmc.webservice.callback.NodeComplementCallbackResponse")
    public String nodeComplementCallback(
        @WebParam(name = "arg0", targetNamespace = "")
        com.vispractice.fmc.webservice.callback.WorkFlowParms arg0
    );
}
