
package com.vispractice.fmc.csb.sb_wf_inquirytasksrv;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SBWFInquiryTaskSrvService", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_InquiryTaskSrv", wsdlLocation = "http://10.204.115.56:8080/ws/sbWFInquiryTaskSrv/sbWFInquiryTaskSrv.wsdl")
public class SBWFInquiryTaskSrvService
    extends Service
{

    private final static URL SBWFINQUIRYTASKSRVSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.vispractice.fmc.csb.sb_wf_inquirytasksrv.SBWFInquiryTaskSrvService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.vispractice.fmc.csb.sb_wf_inquirytasksrv.SBWFInquiryTaskSrvService.class.getResource(".");
            url = new URL(baseUrl, "http://10.204.115.56:8080/ws/sbWFInquiryTaskSrv/sbWFInquiryTaskSrv.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.204.115.56:8080/ws/sbWFInquiryTaskSrv/sbWFInquiryTaskSrv.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SBWFINQUIRYTASKSRVSERVICE_WSDL_LOCATION = url;
    }

    public SBWFInquiryTaskSrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    public SBWFInquiryTaskSrvService(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://csb.fmc.vispractice.com/SB_WF_InquiryTaskSrv", "SBWFInquiryTaskSrvService"));
    }
    public SBWFInquiryTaskSrvService() {
        super(SBWFINQUIRYTASKSRVSERVICE_WSDL_LOCATION, new QName("http://csb.fmc.vispractice.com/SB_WF_InquiryTaskSrv", "SBWFInquiryTaskSrvService"));
    }

    /**
     * 
     * @return
     *     returns SBWFInquiryTaskSrv
     */
    @WebEndpoint(name = "SBWFInquiryTaskSrvSoap11")
    public SBWFInquiryTaskSrv getSBWFInquiryTaskSrvSoap11() {
        return super.getPort(new QName("http://csb.fmc.vispractice.com/SB_WF_InquiryTaskSrv", "SBWFInquiryTaskSrvSoap11"), SBWFInquiryTaskSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBWFInquiryTaskSrv
     */
    @WebEndpoint(name = "SBWFInquiryTaskSrvSoap11")
    public SBWFInquiryTaskSrv getSBWFInquiryTaskSrvSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://csb.fmc.vispractice.com/SB_WF_InquiryTaskSrv", "SBWFInquiryTaskSrvSoap11"), SBWFInquiryTaskSrv.class, features);
    }

}
