
package com.vispractice.fmc.csb.sb_wf_inquirytasksrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SBWFInquiryTaskSrv", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_InquiryTaskSrv")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SBWFInquiryTaskSrv {


    /**
     * 
     * @param processRequest
     * @return
     *     returns com.vispractice.fmc.csb.sb_wf_inquirytasksrv.ProcessResponse
     */
    @WebMethod
    @WebResult(name = "processResponse", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_InquiryTaskSrv", partName = "processResponse")
    public ProcessResponse process(
        @WebParam(name = "processRequest", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_InquiryTaskSrv", partName = "processRequest")
        ProcessRequest processRequest);

}
