package com.vispractice.fmc.webservice.callback;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.14-SNAPSHOT-88db31a177cff3d0b288bceced1907ad66f447e4
 * 2018-01-24T16:54:52.643+08:00
 * Generated source version: 3.0.14-SNAPSHOT
 * 
 */
@WebServiceClient(name = "easWorkflowCommonCallbackWebservice", 
                  wsdlLocation = "http://10.204.105.164:9015/fssc-eas-web/apis/ws/fssc/eas/callback/easWorkFlowCommonCallback?wsdl",
                  targetNamespace = "http://soap.f10.vispractice.com/fssc/eas/boe/core") 
public class EasWorkflowCommonCallbackWebservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.f10.vispractice.com/fssc/eas/boe/core", "easWorkflowCommonCallbackWebservice");
    public final static QName EasWorkflowCommonCallbackWebserviceImplPort = new QName("http://soap.f10.vispractice.com/fssc/eas/boe/core", "EasWorkflowCommonCallbackWebserviceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.204.105.164:9015/fssc-eas-web/apis/ws/fssc/eas/callback/easWorkFlowCommonCallback?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EasWorkflowCommonCallbackWebservice.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.204.105.164:9015/fssc-eas-web/apis/ws/fssc/eas/callback/easWorkFlowCommonCallback?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EasWorkflowCommonCallbackWebservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EasWorkflowCommonCallbackWebservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EasWorkflowCommonCallbackWebservice() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EasWorkflowCommonCallbackWebservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EasWorkflowCommonCallbackWebservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EasWorkflowCommonCallbackWebservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IEasWorkflowCommonCallbackWebservice
     */
    @WebEndpoint(name = "EasWorkflowCommonCallbackWebserviceImplPort")
    public IEasWorkflowCommonCallbackWebservice getEasWorkflowCommonCallbackWebserviceImplPort() {
        return super.getPort(EasWorkflowCommonCallbackWebserviceImplPort, IEasWorkflowCommonCallbackWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEasWorkflowCommonCallbackWebservice
     */
    @WebEndpoint(name = "EasWorkflowCommonCallbackWebserviceImplPort")
    public IEasWorkflowCommonCallbackWebservice getEasWorkflowCommonCallbackWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(EasWorkflowCommonCallbackWebserviceImplPort, IEasWorkflowCommonCallbackWebservice.class, features);
    }

}
