
package com.vispractice.fmc.webservice.callback;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.14-SNAPSHOT-88db31a177cff3d0b288bceced1907ad66f447e4
 * 2018-01-24T16:54:52.624+08:00
 * Generated source version: 3.0.14-SNAPSHOT
 * 
 */
 
public class IEasWorkflowCommonCallbackWebservice_EasWorkflowCommonCallbackWebserviceImplPort_Server{

    protected IEasWorkflowCommonCallbackWebservice_EasWorkflowCommonCallbackWebserviceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new EasWorkflowCommonCallbackWebserviceImplPortImpl();
        String address = "http://localhost:9015/fssc-eas-web/apis/ws/fssc/eas/callback/easWorkFlowCommonCallback";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IEasWorkflowCommonCallbackWebservice_EasWorkflowCommonCallbackWebserviceImplPort_Server();
        System.out.println("Server ready..."); 
        
//        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
//        System.exit(0);
    }
}
