package com.vispractice.fmc.csb.sb_wf_inquiryprocessstatussrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.14-SNAPSHOT-88db31a177cff3d0b288bceced1907ad66f447e4
 * 2017-09-01T17:10:58.119+08:00
 * Generated source version: 3.0.14-SNAPSHOT
 * 
 */
@WebServiceClient(name = "SBWFInquiryProcessStatusSrvService", 
                  wsdlLocation = "http://10.204.115.56:8080/ws/sbWFInquiryProcessStatusSrv/sbWFInquiryProcessStatusSrv.wsdl",
                  targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_InquiryProcessStatusSrv") 
public class SBWFInquiryProcessStatusSrvService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://csb.fmc.vispractice.com/SB_WF_InquiryProcessStatusSrv", "SBWFInquiryProcessStatusSrvService");
    public final static QName SBWFInquiryProcessStatusSrvSoap11 = new QName("http://csb.fmc.vispractice.com/SB_WF_InquiryProcessStatusSrv", "SBWFInquiryProcessStatusSrvSoap11");
    static {
        URL url = null;
        try {
            url = new URL("http://10.204.115.56:8080/ws/sbWFInquiryProcessStatusSrv/sbWFInquiryProcessStatusSrv.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SBWFInquiryProcessStatusSrvService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.204.115.56:8080/ws/sbWFInquiryProcessStatusSrv/sbWFInquiryProcessStatusSrv.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SBWFInquiryProcessStatusSrvService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBWFInquiryProcessStatusSrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBWFInquiryProcessStatusSrvService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SBWFInquiryProcessStatusSrvService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SBWFInquiryProcessStatusSrvService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SBWFInquiryProcessStatusSrvService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SBWFInquiryProcessStatusSrv
     */
    @WebEndpoint(name = "SBWFInquiryProcessStatusSrvSoap11")
    public SBWFInquiryProcessStatusSrv getSBWFInquiryProcessStatusSrvSoap11() {
        return super.getPort(SBWFInquiryProcessStatusSrvSoap11, SBWFInquiryProcessStatusSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBWFInquiryProcessStatusSrv
     */
    @WebEndpoint(name = "SBWFInquiryProcessStatusSrvSoap11")
    public SBWFInquiryProcessStatusSrv getSBWFInquiryProcessStatusSrvSoap11(WebServiceFeature... features) {
        return super.getPort(SBWFInquiryProcessStatusSrvSoap11, SBWFInquiryProcessStatusSrv.class, features);
    }

}
