package com.vispractice.fmc.csb.sb_wf_approvalsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.14-SNAPSHOT-88db31a177cff3d0b288bceced1907ad66f447e4
 * 2017-09-01T17:19:05.908+08:00
 * Generated source version: 3.0.14-SNAPSHOT
 * 
 */
@WebServiceClient(name = "SBWFApprovalSrvService", 
                  wsdlLocation = "http://10.204.115.56:8080/ws/sbWFApprovalSrv/sbWFApprovalSrv.wsdl",
                  targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv") 
public class SBWFApprovalSrvService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv", "SBWFApprovalSrvService");
    public final static QName SBWFApprovalSrvSoap11 = new QName("http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv", "SBWFApprovalSrvSoap11");
    static {
        URL url = null;
        try {
            url = new URL("http://10.204.115.56:8080/ws/sbWFApprovalSrv/sbWFApprovalSrv.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SBWFApprovalSrvService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.204.115.56:8080/ws/sbWFApprovalSrv/sbWFApprovalSrv.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SBWFApprovalSrvService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBWFApprovalSrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBWFApprovalSrvService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SBWFApprovalSrvService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SBWFApprovalSrvService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SBWFApprovalSrvService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SBWFApprovalSrv
     */
    @WebEndpoint(name = "SBWFApprovalSrvSoap11")
    public SBWFApprovalSrv getSBWFApprovalSrvSoap11() {
        return super.getPort(SBWFApprovalSrvSoap11, SBWFApprovalSrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBWFApprovalSrv
     */
    @WebEndpoint(name = "SBWFApprovalSrvSoap11")
    public SBWFApprovalSrv getSBWFApprovalSrvSoap11(WebServiceFeature... features) {
        return super.getPort(SBWFApprovalSrvSoap11, SBWFApprovalSrv.class, features);
    }

}
