package com.vispractice.fmc.csb.sb_wf_approvalsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.14-SNAPSHOT-88db31a177cff3d0b288bceced1907ad66f447e4
 * 2017-09-01T17:19:05.862+08:00
 * Generated source version: 3.0.14-SNAPSHOT
 * 
 */
@WebService(targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv", name = "SBWFApprovalSrv")
@XmlSeeAlso({ObjectFactory.class, com.vispractice.fmc.csb.extendparamcollection.ObjectFactory.class, com.vispractice.fmc.csb.msgheader.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBWFApprovalSrv {

    @WebResult(name = "processResponse", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv", partName = "processResponse")
    @WebMethod
    public ProcessResponse process(
        @WebParam(partName = "processRequest", name = "processRequest", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv")
        ProcessRequest processRequest
    );
}
