package com.vispractice.fmc.webservice.processsrv.sb_wf_approvalsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.vispractice.fmc.csb.sb_wf_approvalsrv.ObjectFactory;
import com.vispractice.fmc.csb.sb_wf_approvalsrv.ProcessRequest;
import com.vispractice.fmc.csb.sb_wf_approvalsrv.ProcessResponse;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-08T18:21:53.603+08:00
 * Generated source version: 3.1.12
 */
@WebService(targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv", name = "SBWFApprovalSrv")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBWFApprovalSrv {
    @WebResult(name = "processResponse", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv", partName = "processResponse")
    @WebMethod
    public ProcessResponse process(
        @WebParam(partName = "processRequest", name = "processRequest", targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv")
        ProcessRequest processRequest
    );
}
