package com.vispractice.fmc.webservice.processsrv.sb_wf_approvalsrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.vispractice.fmc.webservice.support.SimulateHelper;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-08T18:21:53.613+08:00
 * Generated source version: 3.1.12
 */
@WebServiceClient(name = "SBWFApprovalSrvService", 
                  wsdlLocation = "http://10.204.115.52:8080/ws/sbWFApprovalSrv/sbWFApprovalSrv.wsdl",
                  targetNamespace = "http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv") 
public class SBWFApprovalSrvService extends Service {
    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv", "SBWFApprovalSrvService");
    public final static QName SBWFApprovalSrvSoap11 = new QName("http://csb.fmc.vispractice.com/SB_WF_ApprovalSrv", "SBWFApprovalSrvSoap11");
    
    static {
        URL url = null;
        try {
            url = new URL(SimulateHelper.getURI()+"/ws/sbWFApprovalSrv/sbWFApprovalSrv.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SBWFApprovalSrvService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.204.115.52:8080/ws/sbWFApprovalSrv/sbWFApprovalSrv.wsdl");
        }
        
        WSDL_LOCATION = url;
    }

    public SBWFApprovalSrvService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SBWFApprovalSrvService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBWFApprovalSrvService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SBWFApprovalSrvService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SBWFApprovalSrvService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SBWFApprovalSrvService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     * @return
     * returns SBWFApprovalSrv
     */
    @WebEndpoint(name = "SBWFApprovalSrvSoap11")
    public SBWFApprovalSrv getSBWFApprovalSrvSoap11() {
        return super.getPort(SBWFApprovalSrvSoap11, SBWFApprovalSrv.class);
    }

    /**
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBWFApprovalSrv
     */
    @WebEndpoint(name = "SBWFApprovalSrvSoap11")
    public SBWFApprovalSrv getSBWFApprovalSrvSoap11(WebServiceFeature... features) {
        return super.getPort(SBWFApprovalSrvSoap11, SBWFApprovalSrv.class, features);
    }
}